config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  f_config:
    src: config/xmodmap/config
    dst: ~/.config/xmodmap/config
  f_grub:
    src: etc/default/grub
    dst: /etc/default/grub
  f_logind.conf:
    src: etc/systemd/logind.conf
    dst: /etc/systemd/logind.conf
  f_sleep.conf:
    src: etc/systemd/sleep.conf
    dst: /etc/systemd/sleep.conf
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  f_user-dirs.dirs:
    src: config/user-dirs.dirs
    dst: ~/.config/user-dirs.dirs
  f_zshrc:
    src: config/zsh/.zshrc
    dst: ~/.config/zsh/.zshrc
  f_pacman.conf:
    src: etc/pacman.conf
    dst: /etc/pacman.conf
  f_wgetrc:
    src: config/wgetrc
    dst: ~/.config/wgetrc
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_optimus-manager.conf:
    src: etc/optimus-manager/optimus-manager.conf
    dst: /etc/optimus-manager/optimus-manager.conf
  f_main.conf:
    src: etc/bluetooth/main.conf
    dst: /etc/bluetooth/main.conf
  f_config.ini:
    src: config/networkmanager-dmenu/config.ini
    dst: ~/.config/networkmanager-dmenu/config.ini
  f_mpv.conf:
    src: config/mpv/mpv.conf
    dst: ~/.config/mpv/mpv.conf
  f_99-lowbat.rules:
    src: etc/udev/rules.d/99-lowbat.rules
    dst: /etc/udev/rules.d/99-lowbat.rules
    chmod: '755'
  f_hibernate-if-low.sh:
    src: bin/hibernate-if-low.sh
    dst: /bin/hibernate-if-low.sh
    chmod: '755'
  f_auto-hibernate.service:
    src: etc/systemd/system/auto-hibernate.service
    dst: /etc/systemd/system/auto-hibernate.service
    chmod: '755'
  f_auto-hibernate.timer:
    src: etc/systemd/system/auto-hibernate.timer
    dst: /etc/systemd/system/auto-hibernate.timer
    chmod: '755'
  f_backlight.rules:
    src: etc/udev/rules.d/backlight.rules
    dst: /etc/udev/rules.d/backlight.rules
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
    chmod: '755'
  f_profile:
    src: profile
    dst: ~/.profile
    chmod: '755'
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_smb.conf:
    src: etc/samba/smb.conf
    dst: /etc/samba/smb.conf
  f_notmuch-config:
    src: notmuch-config
    dst: ~/.notmuch-config
  f_neomuttrc:
    src: config/neomutt/neomuttrc
    dst: ~/.config/neomutt/neomuttrc
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: '700'
  d_gtk-2.0:
    src: config/gtk-2.0
    dst: ~/.config/gtk-2.0
    chmod: '700'
  d_gtk-4.0:
    src: config/gtk-4.0
    dst: ~/.config/gtk-4.0
  f_index.theme:
    src: icons/default/index.theme
    dst: ~/.icons/default/index.theme
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_lightdm.conf:
    src: etc/lightdm/lightdm.conf
    dst: /etc/lightdm/lightdm.conf
  f_lightdm-webkit2-greeter.conf:
    src: etc/lightdm/lightdm-webkit2-greeter.conf
    dst: /etc/lightdm/lightdm-webkit2-greeter.conf
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  f_fcitx_profile:
    src: config/fcitx/profile
    dst: ~/.config/fcitx/profile
  f_fcitx-xkb.config:
    src: config/fcitx/conf/fcitx-xkb.config
    dst: ~/.config/fcitx/conf/fcitx-xkb.config
  f_fcitx-classic-ui.config:
    src: config/fcitx/conf/fcitx-classic-ui.config
    dst: ~/.config/fcitx/conf/fcitx-classic-ui.config
  f_xmodmap:
    src: config/fcitx/data/xmodmap
    dst: ~/.config/fcitx/data/xmodmap
  f_locale.gen:
    src: etc/locale.gen
    dst: /etc/locale.gen
  f_kanshi_config:
    src: config/kanshi/config
    dst: ~/.config/kanshi/config
  f_sxhkdrc:
    src: config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
  f_exwm.desktop:
    src: usr/share/xsessions/exwm.desktop
    dst: /usr/share/xsessions/exwm.desktop
  f_dwm.desktop:
    src: usr/share/xsessions/dwm.desktop
    dst: /usr/share/xsessions/dwm.desktop
  f_xmonad.hs:
    src: xmonad/xmonad.hs
    dst: ~/.xmonad/xmonad.hs
  f_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_conky:
    src: config/conky
    dst: ~/.config/conky
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  f_userchrome.css:
    src: config/firefox/chrome/userChrome.css
    dst: ~/.config/firefox/chrome/userChrome.css
  d_flameshot:
    src: config/flameshot
    dst: ~/.config/flameshot
  f_spotify.desktop:
    src: usr/share/applications/spotify.desktop
    dst: /usr/share/applications/spotify.desktop
  f_nsxiv.desktop:
    src: usr/share/applications/nsxiv.desktop
    dst: /usr/share/applications/nsxiv.desktop
    chmod: '755'
  f_key-handler:
    src: config/nsxiv/exec/key-handler
    dst: ~/.config/nsxiv/exec/key-handler
    chmod: '755'
  f_post_script.sh:
    src: config/pywal/post_script.sh
    dst: ~/.config/pywal/post_script.sh
    chmod: '755'
  f_coc-settings.json:
    src: config/nvim/coc-settings.json
    dst: ~/.config/nvim/coc-settings.json
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_wal:
    src: cache/wal
    dst: ~/.cache/wal
  d_emacs.d:
    src: emacs.d
    dst: ~/.emacs.d
    chmod: '700'
  f_plug.vim:
    src: local/share/nvim/site/autoload/plug.vim
    dst: ~/.local/share/nvim/site/autoload/plug.vim
  f_gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  d_backgrounds:
    src: Backgrounds
    dst: ~/Backgrounds
  f_git_config:
    src: config/git/config
    dst: ~/.config/git/config
  d_extensions:
    src: config/coc/extensions
    dst: ~/.config/coc/extensions
  f_memos.json:
    src: config/coc/memos.json
    dst: ~/.config/coc/memos.json
  f_suggest.txt:
    src: config/coc/suggest.txt
    dst: ~/.config/coc/suggest.txt
  f_cava_config:
    src: config/cava/config
    dst: ~/.config/cava/config
  f_config.py:
    src: config/qtile/config.py
    dst: ~/.config/qtile/config.py
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  f_kritarc:
    src: config/kritarc
    dst: ~/.config/kritarc
    chmod: '600'
  f_grub.cfg:
    src: boot/grub/grub.cfg
    dst: /boot/grub/grub.cfg
    chmod: '755'
  d_litarvan:
    src: usr/share/lightdm-webkit/themes/litarvan
    dst: /usr/share/lightdm-webkit/themes/litarvan
profiles:
  MattArchSudo:
    dotfiles:
    - f_grub
    - f_logind.conf
    - f_sleep.conf
    - f_pacman.conf
    - f_optimus-manager.conf
    - f_main.conf
    - f_99-lowbat.rules
    - f_hibernate-if-low.sh
    - f_auto-hibernate.service
    - f_auto-hibernate.timer
    - f_backlight.rules
    - f_smb.conf
    - f_lightdm.conf
    - f_lightdm-webkit2-greeter.conf
    - f_locale.gen
    - f_exwm.desktop
    - f_dwm.desktop
    - f_spotify.desktop
    - f_nsxiv.desktop
    - f_grub.cfg
    - d_litarvan

  MattArch:
    dotfiles:
    - d_polybar
    - f_config
    - f_mimeapps.list
    - f_user-dirs.dirs
    - f_zshrc
    - f_wgetrc
    - f_alacritty.yml
    - f_config.ini
    - f_mpv.conf
    - f_xprofile
    - f_profile
    - f_zshenv
    - f_notmuch-config
    - f_neomuttrc
    - d_gtk-3.0
    - d_gtk-2.0
    - d_gtk-4.0
    - f_index.theme
    - f_xresources
    - f_picom.conf
    - f_fcitx_profile
    - f_fcitx-xkb.config
    - f_fcitx-classic-ui.config
    - f_xmodmap
    - f_kanshi_config
    - f_sxhkdrc
    - f_xmonad.hs
    - f_config.rasi
    - d_dunst
    - d_conky
    - d_ranger
    - f_userchrome.css
    - d_flameshot
    - f_key-handler
    - f_post_script.sh
    - f_coc-settings.json
    - d_nvim
    - d_wal
    - d_emacs.d
    - f_plug.vim
    - f_gtkrc-2.0
    - d_backgrounds
    - f_git_config
    - d_extensions
    - f_memos.json
    - f_suggest.txt
    - f_cava_config
    - f_config.py
    - d_sway
    - d_waybar
    - f_kritarc
