#+title: Emacs Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ~/.emacs.d/init.el :results none mkdirp: yes
* Early Init
** Increase Garbage Collection Threshold
*NOTE:* The default is 800 kilobytes. The threshold is measured in bytes.
#+begin_src emacs-lisp
(setq gc-cons-threshold (* 1 1000 1000 1000))
;; (setq garbage-collection-messages t)
#+end_src

** Startup Performance
#+begin_src emacs-lisp
(defvar file-name-handler-alist-original file-name-handler-alist)
(setq file-name-handler-alist nil)
#+end_src

* Init
** Package Management
*** Specify Load Path
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp")
#+end_src

*** Enable AOT Compilation of External Packages
#+begin_src emacs-lisp
(setq package-native-compile t)
#+end_src

*** Setup Package Sources
#+begin_src emacs-lisp
(require 'package)
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("org" . "https://orgmode.org/elpa/")
        ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
#+end_src

*** Setup Use-Package
#+begin_src emacs-lisp
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)
#+end_src

*** Automatic Package Updates
#+begin_src emacs-lisp
(use-package auto-package-update
  :after gcmh
  :custom
  (auto-package-update-hide-results t)
  :config
  (auto-package-update-maybe)
  (auto-package-update-at-time "09:00"))
#+end_src

** Utilities
*** No Littering
#+begin_src emacs-lisp
(use-package no-littering
  :config
  (setq auto-save-file-name-transforms
      `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (setq make-backup-files nil)
  (setq auto-save-default nil))
#+end_src

** Performance Improvements
*** Asynchronous Processes
#+begin_src emacs-lisp
(use-package async
  :init (dired-async-mode 1))
#+end_src

** User Interface
*** Basic Configuration
#+begin_src emacs-lisp

;; Don't show startup menu
(setq inhibit-startup-message t)
     
;; Don't ask to kill processes when exiting
(setq confirm-kill-processes nil)

;; Never pop up UI dialogs
(setq use-dialog-box nil)

;; Disable Terminal Bell
(setq ring-bell-function 'ignore)

;; Revert buffers when the underlying file has changed
(global-auto-revert-mode 1)

;; Use yes/no abbreviations in minibuffer prompts
(fset 'yes-or-no-p 'y-or-n-p)

(blink-cursor-mode 0) ;; Don't blink cursor
(scroll-bar-mode 0)   ;; Remove scroll bar
(tool-bar-mode 0)     ;; Remove toolbar
(tooltip-mode 0)      ;; Remove tooltip
(menu-bar-mode 0)     ;; Remove menubar

(set-fringe-mode 10)
#+end_src

*** Line Numbers
#+begin_src emacs-lisp
(column-number-mode)
(global-display-line-numbers-mode t)
(setq display-line-numbers-type 'relative)
#+end_src

****  Disable for some Modes
#+begin_src emacs-lisp
(dolist (mode '(term-mode-hook
                org-mode-hook
                markdown-mode-hook
                shell-mode-hook
                eshell-mode-hook
                vterm-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src

*** Good Scrolling
#+begin_src emacs-lisp
(use-package good-scroll
  :config
  (good-scroll-mode 1))
#+end_src

*** Font Configuration
#+begin_src emacs-lisp
;; Set the default pitch face
(set-face-attribute 'default nil
  :family "Hack Nerd Font Mono"
  :height 120)

;; Set the fixed pitch face
(set-face-attribute 'fixed-pitch nil
  :family "Hack Nerd Font Mono"
  :height 1.0)

;; Set the variable pitch face
(set-face-attribute 'variable-pitch nil
  :family "NotoSans Nerd Font"
  :height 1.0)

(use-package mixed-pitch
  :hook (text-mode . mixed-pitch-mode))

(use-package all-the-icons)
#+end_src

*** Default Theme
#+begin_src emacs-lisp
;; Good Dark Themes: doom-moonless doom-tomorrow-night
;; Good Light Themes: doom-acario-light
(use-package doom-themes)

;; Ewal Theme
(use-package ewal-doom-themes
  :config
  (progn (load-theme 'ewal-doom-vibrant t)
         (enable-theme 'ewal-doom-vibrant)))
(use-package ewal-evil-cursors
  :after ewal-doom-themes)
#+end_src

** Characters
*** Set UTF-8 Encoding
#+begin_src emacs-lisp
(setq locale-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
(set-default-coding-systems  'utf-8)
(set-terminal-coding-system  'utf-8)
(set-keyboard-coding-system  'utf-8)
(set-selection-coding-system 'utf-8)
(set-file-name-coding-system 'utf-8)
(set-clipboard-coding-system 'utf-8)
(set-language-environment "UTF-8")
#+end_src

*** Dashboard
#+begin_src emacs-lisp
(use-package dashboard
  :config
  (dashboard-setup-startup-hook)
  (setq dashboard-center-content t)
  ;; (setq dashboard-startup-banner nil)
  (setq dashboard-week-agenda t)
  (setq initial-buffer-choice 
        (lambda () (get-buffer "*dashboard*")))
  (setq dashboard-set-init-info t)
  (setq dashboard-items '((recents . 5)
                          (bookmarks . 5)
                          (projects . 5)
                          (agenda . 5))))
#+end_src

*** Fcitx
#+begin_src emacs-lisp
(use-package fcitx
  :config
  (fcitx-aggressive-setup)
  (setq fcitx-use-dbus t))
#+end_src

** Window Management
*** Frames Only Mode
Makes popup windows appear in new windows rather than frames
#+begin_src emacs-lisp
(use-package frames-only-mode
  :config
  (frames-only-mode))
#+end_src

** Theme Configuration
*** Doom Modeline
*NOTE:* The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.

#+begin_src emacs-lisp
(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom
  (defcustom doom-modeline-hud nil)
  (doom-modeline-window-width-limit '0.25)
  
  (doom-modeline-buffer-file-name-style 'auto)
  (doom-modeline-irc-stylize 'identity)
  (doom-modeline-checker-simple-format t)
  (doom-modeline-vcs-max-length 12)
  (doom-modeline-number-limit 99)
  (doom-modeline-buffer-state-icon nil)
  (doom-modeline-indent-info nil)
  (doom-modeline-persp-icon nil)
  (doom-modeline-workspace-name nil)
  (doom-modeline-lsp nil)
  (doom-modeline-icon t)
  (doom-modeline-color-icon t)
  (doom-modeline-github nil)
  (doom-modeline-env-version nil)
  (doom-modeline-major-mode-icon nil)
  (doom-modeline-major-mode-color-icon nil)
  (doom-modeline-buffer-modification-icon nil)
  (doom-modeline-minor-modes nil)
  (doom-modeline-enable-word-count nil)
  (doom-modeline-gnus-timer nil)
  (doom-modeline-github-timer nil)
  (doom-modeline-buffer-encoding nil))
#+end_src

** Keybinding Configuration
*** Evil Mode
#+begin_src emacs-lisp
(use-package evil
  :init
  (setq evil-want-integration t
        evil-want-keybinding nil
        evil-want-C-u-scroll t
        evil-want-C-i-jump nil)
  :config
  (evil-mode 1)
  (define-key evil-insert-state-map (kbd "C-;") 'evil-normal-state)
  (define-key evil-normal-state-map (kbd "C-;") 'keyboard-quit)
  (define-key evil-insert-state-map (kbd "C-h")
    'evil-delete-backward-char-and-join)

  (define-key evil-motion-state-map
    (kbd "<remap> <evil-next-line>") #'evil-next-visual-line)
  (define-key evil-motion-state-map
    (kbd "<remap> <evil-previous-line>") #'evil-previous-visual-line)
  (define-key evil-operator-state-map
    (kbd "<remap> <evil-next-line>") #'evil-next-line)
  (define-key evil-operator-state-map
    (kbd "<remap> <evil-previous-line>") #'evil-previous-line)
  (global-unset-key (kbd "C-x ESC"))
  (global-unset-key (kbd "C-c ESC")))
#+end_src

**** Disable in Certain Modes
#+begin_src emacs-lisp
;; (dolist (mode '(term-mode-hook
;;                 org-mode-hook
;;                 shell-mode-hook
;;                 eshell-mode-hook
;;                 vterm-mode-hook))
;;   (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src

**** Evil Collection
#+begin_src emacs-lisp
(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))
#+end_src

*** General
#+begin_src emacs-lisp
(use-package general
  :after evil
  :config
  (general-create-definer my/leader-keys
    :keymaps '(normal insert visual emacs)
    :prefix "SPC"
    :global-prefix "C-SPC")

  (my/leader-keys
    "tt" 'counsel-load-theme))
#+end_src

** Autocomplete Modes
*** Ivy
#+begin_src emacs-lisp
(use-package ivy
  :diminish
  :bind (("C-s" . swiper)
         :map ivy-minibuffer-map
         ("TAB" . ivy-alt-done)
         ("C-l" . ivy-alt-done)
         ("C-j" . ivy-next-line)
         ("C-k" . ivy-previous-line)
         :map ivy-switch-buffer-map
         ("C-k" . ivy-previous-line)
         ("C-l" . ivy-done)
         ("C-d" . ivy-switch-buffer-kill)
         :map ivy-reverse-i-search-map
         ("C-k" . ivy-previous-line)
         ("C-d" . ivy-reverse-i-search-kill))
  :config (ivy-mode 1))
#+end_src

**** Ivy-PosFrame
#+begin_src emacs-lisp
(use-package ivy-posframe
  :after ivy
  :config
  (setq ivy-posframe-width (frame-width)
        ivy-posframe-height (/ (frame-height) 5))
  (setq ivy-posframe-display-functions-alist
        '((t . ivy-posframe-display-at-frame-bottom-left)))
  (set-face-attribute
   'ivy-posframe nil
   :foreground "white"
   :background "black")
  (ivy-posframe-mode 1))
#+end_src

**** Ivy Clipmenu
#+begin_src emacs-lisp
(use-package ivy-clipmenu)
#+end_src

**** Ivy-Rich
#+begin_src emacs-lisp
(use-package ivy-rich
  :after ivy
  :init (ivy-rich-mode 1))
#+end_src

**** Ivy-Prescient
#+begin_src emacs-lisp
(use-package ivy-prescient
  :after counsel
  :custom
  (ivy-prescient-enable-filtering nil)
  :config
  (prescient-persist-mode 1)
  (ivy-prescient-mode 1))
#+end_src

*** Counsel
#+begin_src emacs-lisp
(use-package counsel
  :bind (("C-M-j" . 'counsel-switch-buffer)
         :map minibuffer-local-map
         ("C-r" . 'counsel-minibuffer-history))
  :custom
  (counsel-linux-app-format-function
   #'counsel-linux-app-format-function-name-only)
  :config
  (counsel-mode 1))
#+end_src

** Other Modes
*** Helpful
#+begin_src emacs-lisp
(use-package helpful
  :commands (helpful-callable
             helpful-variable
             helpful-command helpful-key)
  :custom
  (counsel-describe-function-function #'helpful-callable)
  (counsel-describe-variable-function #'helpful-variable)
  :bind
  ([remap describe-function] . counsel-describe-function)
  ([remap describe-command] . helpful-command)
  ([remap describe-variable] . counsel-describe-variable)
  ([remap describe-key] . helpful-key))
#+end_src

*** Focus Mode
#+begin_src emacs-lisp
(use-package focus)
#+end_src

*** Solaire Mode
#+begin_src emacs-lisp
(use-package solaire-mode
  :config (solaire-global-mode 1))
#+end_src

** Org Mode
*** Org-Roam
#+begin_src emacs-lisp
(use-package org-roam
  :custom
  (org-roam-directory "~/RoamNotes")
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n i" . org-roam-node-insert))
  :config
  (org-roam-setup))
#+end_src

*** Basic Config
#+begin_src emacs-lisp
(setq-default
 help-window-select t
 debug-on-error t
 indent-tabs-mode nil
 jit-lock-defer-time 0
 window-combination-resize t
 history-delete-duplicates t)

(use-package adaptive-wrap
  :config
  (visual-line-mode 1)
  (adaptive-wrap-prefix-mode 1))

(defun org/setup ()
  (org-indent-mode 1))

(use-package org
  :pin org
  :commands (org-capture org-agenda)
  :hook (org-mode . org/setup)
  :config
  
  ;; Replace list hyphen with dot
  (font-lock-add-keywords
   'org-mode
   '(("^ *\\([-]\\) "
      (0 (prog1 () (compose-region
                    (match-beginning 1)
                    (match-end 1) "•"))))))
  (setq-default
   org-ellipsis " ▾"
   org-pretty-entities t
   org-hide-emphasis-markers t
   org-edit-src-content-indentation 0))
#+end_src

**** Nicer Heading Bullets
[[https://github.com/sabof/org-bullets][org-bullets]] replaces the heading stars in =org-mode= buffers with nicer looking characters that you can control.  Another option for this is [[https://github.com/integral-dw/org-superstar-mode][org-superstar-mode]] which we may cover in a later video.

#+begin_src emacs-lisp
(use-package org-bullets
  :hook (org-mode . org-bullets-mode)
  :custom
  (org-bullets-bullet-list
   '("◉" "○" "●" "○" "●" "○" "●")))
#+end_src

**** Center Org Buffers
#+begin_src emacs-lisp
(setq-default fill-column 80)
(use-package olivetti
  :hook (org-mode . olivetti-mode)
  :hook (markdown-mode . olivetti-mode))
#+end_src

*** Drag and Drop Images
#+begin_src emacs-lisp
(use-package org-download
  :after org
  :config
  (org-download-enable))
#+end_src

*** Latex Support
#+begin_src emacs-lisp
(use-package auctex
  :defer t
  :config
  (setq TeX-auto-save t
        TeX-parse-self t)
  (setq org-format-latex-options (plist-put org-format-latex-options
                                            :scale 2.0)))
#+end_src

*** Configure Babel Languages
#+begin_src emacs-lisp
(with-eval-after-load 'org
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)
     (haskell . t)
     (shell . t)))
  (push '("conf-unix" . conf-unix) org-src-lang-modes))
#+end_src

*** Structure Templates
Org Mode's [[https://orgmode.org/manual/Structure-Templates.html][structure templates]] feature enables you to quickly insert code blocks into your Org files in combination with =org-tempo= by typing =<= followed by the template name like =el= or =py= and then press =TAB=.

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (require 'org-tempo)
  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("hs" . "src haskell")))
#+end_src

*** Auto-tangle Configuration Files
#+begin_src emacs-lisp
(defun babel/tangle-config ()
  (when (member (file-name-nondirectory (buffer-file-name))
                '("emacs.org"
                  "config.org"))
    (let ((org-confirm-babel-evaluate nil)) (org-babel-tangle)))) 

(add-hook 'org-mode-hook
          (lambda () (add-hook 'after-save-hook #'babel/tangle-config)))
#+end_src

*** Org-Alert
#+begin_src emacs-lisp
(use-package org-alert
  :ensure t
  :config
  (setq alert-default-style 'libnotify
        org-alert-notify-cutoff (* 2 24 60 60))
  (org-alert-enable))
#+end_src

** Development
*** Projectile
#+begin_src emacs-lisp
(use-package projectile
  :diminish projectile-mode
  :config (projectile-mode)
  :custom ((projectile-completion-system 'ivy))
  :bind-keymap
  ("C-c p" . projectile-command-map)
  :init
  (setq projectile-project-search-path '("~/Repositories")
        projectile-switch-project-action #'projectile-dired))

(use-package counsel-projectile
  :after projectile
  :config (counsel-projectile-mode))
#+end_src

*** Magit
#+begin_src emacs-lisp
(use-package magit
  :commands magit-status
  :custom
  (magit-display-buffer-function
   #'magit-display-buffer-same-window-except-diff-v1))

;; (use-package forge
;;  :after magit)
#+end_src

*** Evil Commentary
#+begin_src emacs-lisp
(use-package evil-commentary
  :config (evil-commentary-mode))
#+end_src

*** Rainbow Delimiters
#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode)
  :config (show-paren-mode 1))
#+end_src

** Flyspell
*** Popup Buffers
#+begin_src emacs-lisp
(use-package flyspell-correct-popup)
#+end_src bash

*** Start Flyspell with Certain Modes
#+begin_src emacs-lisp
(dolist (hook '(text-mode-hook org-mode-hook))
  (add-hook hook (lambda () (flyspell-mode 1))))
(dolist (hook '(change-log-mode-hook log-edit-mode-hook))
  (add-hook hook (lambda () (flyspell-mode -1))))
(dolist (hook '(python-mode-hook))
  (add-hook hook (lambda () (flyspell-prog-mode 1))))
#+end_src bash

*** Check Spelling On Demand
#+begin_src emacs-lisp
(defun flyspell/english ()
  (interactive)
  (ispell-change-dictionary "english")
  (flyspell-buffer))
  
(defun flyspell/russian ()
  (interactive)
  (ispell-change-dictionary "russian")
  (flyspell-buffer))
#+end_src bash

** Which Key
#+begin_src emacs-lisp
(use-package which-key)
#+end_src

** LSP-Mode
*** Flycheck
#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :defer t
  :init (global-flycheck-mode t))
  #+end_src

*** Basic Setup
#+begin_src emacs-lisp
(defun lsp/mode-setup ()
  (setq lsp-headerline-breadcrumb-segments
        '(path-up-to-project file symbols))
  (lsp-headerline-breadcrumb-mode))

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :hook (lsp-mode . lsp/mode-setup)
  :init
  (setq lsp-keymap-prefix "C-l")
  :config
  (lsp-enable-which-key-integration t))
#+end_src

*** LSP UI
Gives sidelines, documentation popups, and references popups
#+begin_src emacs-lisp
(use-package lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :custom
  (lsp-ui-doc-position 'bottom))
#+end_src

*** LSP Ivy
Allows you to quckly find definitions.
#+begin_src emacs-lisp
(use-package lsp-ivy
  :after lsp)
#+end_src

*** Company Mode
#+begin_src emacs-lisp
(use-package company
  :defer t
  :after lsp
  :init (global-company-mode t)
  :config
  :hook (lsp-mode . company-mode)
  :bind (:map company-active-map
              ("<tab>" . company-complete-selection))
        (:map lsp-mode-map
              ("<tab>" . company-indent-or-complete-common))
  :custom
  (company-minimum-prefix-length 1)
  (company-idle-delay 0.0))
#+end_src

**** Company Box Mode
#+begin_src emacs-lisp
(use-package company-box
  :hook (company-mode . company-box-mode))
#+end_src

** File Managers
*** Dired
#+begin_src emacs-lisp
(use-package dired
  :ensure nil
  :commands (dired dired-jump)
  :bind (("C-x C-j" . dired-jump))
  :custom ((dired-listing-switches "-alh --group-directories-first"))
  :config
  (evil-collection-define-key 'normal 'dired-mode-map
    "h" 'dired-single-up-directory
    "l" 'dired-single-buffer))
#+end_src

**** Prevent Dired from Creating Extra Buffers
#+begin_src emacs-lisp
(use-package dired-single
  :after dired)
#+end_src

****  Dired Icons
#+begin_src emacs-lisp
(use-package all-the-icons-dired
  :hook (dired-mode . all-the-icons-dired-mode))
#+end_src

****  Open Files in External Programs
#+begin_src emacs-lisp
(use-package dired-open
  :after dired
  :config
  (setq dired-open-extensions
        '(("png" . "feh")
          ("mkv" . "mpv"))))

#+end_src

****  Hide/Show Dotfiles
#+begin_src emacs-lisp
(use-package dired-hide-dotfiles
  :hook (dired-mode . dired-hide-dotfiles-mode)
  :config
  (evil-collection-define-key 'normal 'dired-mode-map
    "H" 'dired-hide-dotfiles-mode))
#+end_src

** Languages
*** Vimscript
#+begin_src emacs-lisp
(use-package vimrc-mode
  :mode "\\.vim\\'")
#+end_src

*** Haskell
#+begin_src emacs-lisp
(use-package haskell-mode
  :mode "\\.hs\\'")
#+end_src

*** JSON
#+begin_src emacs-lisp
(use-package json-mode)
#+end_src

*** TypeScript
#+begin_src emacs-lisp
(use-package typescript-mode
  :mode "\\.ts\\'"
  :hook (typescript-mode . lsp-deferred)
  :config
  (setq typescript-indent-level 2))
#+end_src

*** Rust
#+begin_src emacs-lisp
(use-package rust-mode
  :mode "\\.rs\\'"
  :hook (rust-mode-hook . lsp-deferred))
#+end_src

*** Makefile
#+begin_src emacs-lisp
(use-package make-mode
  :mode (("Makefile" . makefile-gmake-mode)))
#+end_src

*** Python
#+begin_src emacs-lisp
(use-package transient)
(use-package pyvenv)
(use-package poetry)
#+end_src

*** Verilog
#+begin_src emacs-lisp :tangle no
(use-package verilog-mode
  :config
  (setq verilog-align-ifelse nil
        verilog-auto-delete-trailing-whitespace nil
        verilog-auto-inst-param-value nil
        verilog-auto-inst-vector nil
        verilog-auto-lineup 'all
        verilog-auto-newline nil
        verilog-auto-save-policy nil
        verilog-auto-template-warn-unused nil
        verilog-highlight-grouping-keywords nil
        verilog-highlight-modules nil
        verilog-tab-to-comment nil))

(eval-after-load 'verilog-mode
    '(progn
        ;; same for all the electric-verilog-* commands in                
        ;; the mode's map (see verilog-mode.el)                      
        (define-key verilog-mode-map (kbd ";") 'self-insert-command)
        (define-key verilog-mode-map (kbd ":") 'self-insert-command)
        (define-key verilog-mode-map (kbd "RET") 'evil-ret)
        (define-key verilog-mode-map (kbd "TAB") 'tab-to-tab-stop)))

(require 'lsp-verilog)
(custom-set-variables
 '(lsp-clients-svlangserver-launchConfiguration "/bin/verilator -sv --lint-only -Wall")
 '(lsp-clients-svlangserver-formatCommand "/bin/verible-verilog-format"))
(add-hook 'verilog-mode-hook #'lsp-deferred)
#+end_src

*** Company Mode
#+begin_src emacs-lisp
(use-package verilog-mode
  :defer t
  :config
  (require 'lsp)
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection '("svls"))
   :major-modes '(verilog-mode)
   :priority -1
   ))
  :hook (verilog-mode . (lambda()
      (lsp)
      (flycheck-mode t)
      (add-to-list 'lsp-language-id-configuration '(verilog-mode . "verilog")))))
#+end_src

*** Makefiles
#+begin_src emacs-lisp
(use-package make-mode
  :mode (("Makefile" . makefile-gmake-mode)))
#+end_src

** Terminals
*** Term Mode
#+begin_src emacs-lisp
(use-package term
  :commands term
  :config
  (setq explicit-shell-file-name "zsh"))
#+end_src

**** Better term-mode colors
*NOTE:* This package requires =ncurses= to be installed on your machine.
#+begin_src emacs-lisp
(use-package eterm-256color
  :hook (term-mode . eterm-256color-mode))
#+end_src

*** Vterm
#+begin_src emacs-lisp
(use-package vterm
  :commands vterm
  :config
  (setq vterm-shell "zsh")
  (setq vterm-max-scrollback 10000))
#+end_src

** Closing Configuration
*** Enable File Name Handler
#+begin_src emacs-lisp
(setq file-name-handler-alist
      file-name-handler-alist-original)
#+end_src

*** Enable Garbage Collector Magic Hack
#+begin_src emacs-lisp
(use-package gcmh
  :config
  (setq gcmh-high-cons-threshold (* 100 1000 1000))
  (gcmh-mode 1))
#+end_src
