;;; ewal-doom-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from ewal-doom-one-theme.el

(register-definition-prefixes "ewal-doom-one-theme" '("ewal-doom-one"))


;;; Generated autoloads from ewal-doom-themes.el

(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "ewal-doom-themes" '("ewal-doom-themes-get-color"))


;;; Generated autoloads from ewal-doom-vibrant-theme.el

(register-definition-prefixes "ewal-doom-vibrant-theme" '("ewal-doom-"))

;;; End of scraped data

(provide 'ewal-doom-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; ewal-doom-themes-autoloads.el ends here
