;; -*- emacs-lisp -*- <22/05/19 02:22:43 /home/mwglen/.emacs.d/var/tramp/persistency.el>
;; Tramp connection history.  Don't change this file.
;; Run `M-x tramp-cleanup-all-connections' instead.

(((tramp-file-name "ssh" "mwglen" nil "grendel.ece.ncsu.edu" nil nil nil)
  ("null-device" "/dev/null")
  ("uname" "Linux 3.10.0-1160.62.1.el7.x86_64")
  ("locale" "LC_ALL=en_US.utf8")
  ("test" "test")
  ("remote-path"
   ("/usr/bin" "/bin" "/sbin" "/usr/sbin" "/usr/local/bin" "/usr/local/sbin"))
  ("pipe-buf" 4096)
  ("remote-shell" "/bin/sh")
  ("~" "/afs/unity.ncsu.edu/users/m/mwglen")
  ("file-exists" "test -e")
  ("case-insensitive" nil)
  ("readlink" "\\readlink")
  ("stat" "env QUOTING_STYLE=locale \\stat")
  ("id" "/usr/bin/id")
  ("gid-integer" 108)
  ("gid-string" "NCSU")
  ("uid-string" "mwglen")
  ("ls" "/usr/bin/ls --color=never")
  ("ls--quoting-style=literal --show-control-chars" "--quoting-style=literal --show-control-chars")
  ("ls--dired" "--dired")
  ("df-blocksize" 1)
  ("df" "\\df --block-size=1 --output=size,used,avail")
  ("bzr" nil)
  ("git" "\\git")
  ("hg" nil)
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("uid-integer" 286931)
  ("ln" "\\ln"))
 ((tramp-file-name "sudo" "mwglen" nil "MattArch" nil nil nil)
  nil))
