;;; Automatically generated by ‘recentf’ on Thu May 19 02:22:43 2022.

(setq recentf-list
      '(
        "/home/mwglen/config.org"
        "/home/mwglen/notes.org"
        "/home/mwglen/questions"
        "/home/mwglen/apartment.org"
        "/home/mwglen/Writing/coda/outline.org"
        "/home/mwglen/emacs.org"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/environment_packages/i2cmb_env_pkg/src/i2cmb_test.svh"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/project_benches/proj_4/testbench/top.sv"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/interface_packages/wb_pkg/src/wb_agent.svh"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/environment_packages/i2cmb_env_pkg/src/i2cmb_env_configuration.svh"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/environment_packages/i2cmb_env_pkg/src/i2cmb_scoreboard.svh"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/environment_packages/i2cmb_env_pkg/src/i2cmb_generator.svh"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/interface_packages/i2c_pkg/src/i2c_driver.svh"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/interface_packages/i2c_pkg/src/i2c_if.sv"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/environment_packages/i2cmb_env_pkg/src/i2cmb_predictor.svh"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/environment_packages/i2cmb_env_pkg/src/i2cmb_environment.svh"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/interface_packages/wb_pkg/src/wb_configuration.svh"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/interface_packages/i2c_pkg/src/i2c_configuration.svh"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/interface_packages/i2c_pkg/src/i2c_transaction.svh"
        "/ssh:mwglen@grendel.ece.ncsu.edu:/afs/unity.ncsu.edu/users/m/mwglen/ECE745-Project/verification_ip/interface_packages/i2c_pkg/src/i2c_monitor.svh"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
