# Shell variables
# Generated by 'wal'
wallpaper='/home/mwglen/.config/wpg/wallpapers/asuka_stairs.jpg'

# Special
background='#150f0d'
foreground='#d9c8ce'
cursor='#d9c8ce'

# Colors
color0='#150f0d'
color1='#D89664'
color2='#C67045'
color3='#D7A292'
color4='#AE704F'
color5='#c0574a'
color6='#BB926A'
color7='#d9c8ce'
color8='#978c90'
color9='#D89664'
color10='#C67045'
color11='#D7A292'
color12='#AE704F'
color13='#eb614d'
color14='#BB926A'
color15='#d9c8ce'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
