# Shell variables
# Generated by 'wal'
wallpaper='/home/mwglen/.config/wpg/wallpapers/asuka_stairs.jpg'

# Special
background='#150f0d'
foreground='#d9c8ce'
cursor='#d9c8ce'

# Colors
color0='#150f0d'
color1='#AE704F'
color2='#C67045'
color3='#BB926A'
color4='#D89664'
color5='#B97490'
color6='#D7A292'
color7='#d9c8ce'
color8='#978c90'
color9='#AE704F'
color10='#C67045'
color11='#BB926A'
color12='#D89664'
color13='#B97490'
color14='#D7A292'
color15='#d9c8ce'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
