--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mwglen/.config/wpg/wallpapers/asuka_stairs.jpg"

-- Special
background="#150f0d"
foreground="#d9c8ce"
cursor="#d9c8ce"

-- Colors
color0="#150f0d"
color1="#D89664"
color2="#C67045"
color3="#D7A292"
color4="#AE704F"
color5="#c0574a"
color6="#BB926A"
color7="#d9c8ce"
color8="#978c90"
color9="#D89664"
color10="#C67045"
color11="#D7A292"
color12="#AE704F"
color13="#eb614d"
color14="#BB926A"
color15="#d9c8ce"
