--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mwglen/.config/wpg/wallpapers/2001_A_Space_Odyssey-artistic.jpg"

-- Special
background="#0a0409"
foreground="#f5d8a6"
cursor="#f5d8a6"

-- Colors
color0="#0a0409"
color1="#9B2E33"
color2="#C9473A"
color3="#99374F"
color4="#B14856"
color5="#DD615B"
color6="#F79D62"
color7="#f5d8a6"
color8="#ab9774"
color9="#9B2E33"
color10="#C9473A"
color11="#99374F"
color12="#B14856"
color13="#DD615B"
color14="#F79D62"
color15="#f5d8a6"
