# Shell variables
# Generated by 'wal'
wallpaper='/home/mwglen/Backgrounds/nge.jpeg'

# Special
background='#0d0f12'
foreground='#ddb4b8'
cursor='#ddb4b8'

# Colors
color0='#0d0f12'
color1='#6C3E43'
color2='#5A4147'
color3='#754245'
color4='#8F4548'
color5='#B64F56'
color6='#BF555B'
color7='#ddb4b8'
color8='#9a7d80'
color9='#6C3E43'
color10='#5A4147'
color11='#754245'
color12='#8F4548'
color13='#B64F56'
color14='#BF555B'
color15='#ddb4b8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
