--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mwglen/.config/wpg/wallpapers/nge.jpeg"

-- Special
background="#0d0f12"
foreground="#ddb4b8"
cursor="#ddb4b8"

-- Colors
color0="#0d0f12"
color1="#6C3E43"
color2="#5A4147"
color3="#754245"
color4="#8F4548"
color5="#B64F56"
color6="#BF555B"
color7="#ddb4b8"
color8="#9a7d80"
color9="#6C3E43"
color10="#5A4147"
color11="#754245"
color12="#8F4548"
color13="#B64F56"
color14="#BF555B"
color15="#ddb4b8"
