config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_vimix:
    src: boot/grub/themes/Vimix
    dst: /boot/grub/themes/Vimix
profiles:
  MattArchSudo:
    dotfiles:
    - d_vimix
